modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="fabulousfletching"
version="1.0.0"
displayName="FabulousFletching"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="prcri, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fabulousfletching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration